# Generated by Django 3.0.6 on 2020-06-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlist',
            old_name='student_name',
            new_name='sname',
        ),
    ]
