# Generated by Django 3.0.6 on 2020-06-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_auto_20200604_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='sroll',
            field=models.CharField(default='enter rno', max_length=10),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='ssec',
            field=models.CharField(default='enter sec', max_length=10),
        ),
    ]
