# Generated by Django 3.0.6 on 2020-06-05 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_auto_20200605_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('sroll', models.CharField(max_length=25)),
                ('sname', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='sroll',
            field=models.CharField(default="enter rno in '18H51A05C.' format", max_length=10),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='ssec',
            field=models.CharField(default="enter sec in 'sec_a' format", max_length=10),
        ),
    ]
