# Generated by Django 3.0.6 on 2020-06-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_auto_20200605_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
