# Generated by Django 3.0.6 on 2020-06-05 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_remove_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sname',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sroll',
            field=models.CharField(default='', max_length=10),
        ),
    ]
