# Generated by Django 3.0.6 on 2020-06-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_auto_20200605_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
