# Generated by Django 3.0.6 on 2020-06-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='sroll',
            field=models.CharField(default="enter rno in '18H51A05C.' format", max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'sroll')},
        ),
    ]
