# Generated by Django 3.0.6 on 2020-06-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_auto_20200606_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('1', 'present'), ('2', 'absent')], max_length=25),
        ),
    ]
