# Generated by Django 3.0.6 on 2020-06-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0014_auto_20200606_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=25),
        ),
    ]
