# Generated by Django 3.0.6 on 2020-06-06 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0015_auto_20200606_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, editable=False),
        ),
    ]
