# Generated by Django 3.0.6 on 2020-06-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0017_auto_20200606_1822'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
