# Generated by Django 3.0.6 on 2020-06-06 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0018_auto_20200606_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='tattendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sroll', models.CharField(default='', max_length=10)),
                ('sname', models.CharField(default='', max_length=25)),
                ('date', models.DateTimeField(default=datetime.date.today, editable=False)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
