# Generated by Django 3.0.6 on 2020-06-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0019_tattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattendance',
            name='status',
            field=models.IntegerField(),
        ),
    ]
