# Generated by Django 3.0.6 on 2020-06-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0021_auto_20200608_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tattendance',
            name='subject',
            field=models.CharField(default='', max_length=25),
        ),
    ]
