# Generated by Django 3.0.6 on 2020-06-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0022_auto_20200608_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='tattendance',
            name='status',
            field=models.CharField(default='', max_length=25),
        ),
    ]
