# Generated by Django 3.0.6 on 2020-06-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0023_auto_20200608_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='tattendance',
            name='date',
            field=models.CharField(default='', max_length=25),
        ),
    ]
