# Generated by Django 3.0.6 on 2020-06-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0025_auto_20200609_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tattendance',
            name='date',
            field=models.DateField(),
        ),
    ]
