# Generated by Django 3.0.6 on 2020-06-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0027_auto_20200609_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='sroll',
            field=models.CharField(default="enter rno in '18H51A05C.' format", max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='ssec',
            field=models.CharField(default="enter sec in 'sec_a' format", max_length=10),
        ),
    ]
